### ISSUE TITLE
Unicode symbols seem to lead to issues

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/paper-abstract-formatter#2]
Example abstract:

> System auditing is a central concern when investigating and responding to security incidents. Unfortunately, attackers regularly engage in anti-forensic activities after a break-in, covering their tracks from the system logs in order to frustrate the efforts of investigators. While a variety of tamper-evident logging solutions have appeared throughout the industry and the literature, these techniques do not meet the operational and scalability requirements of system-layer audit frameworks. In this work, we introduce CUSTOS, a practical framework for the detection of tampering in system logs. CUSTOS consists of a tamper-evident logging layer and a decentralized auditing protocol. The former enables the verification of log integrity with minimal changes to the underlying logging framework, while the latter enables near real-time detection of log integrity violations within an enterprise-class network. CUSTOS is made practical by the observation that we can decouple the costs of cryptographic log commitments from the act of creating and storing log events, without trading off security, leveraging features of off-the-shelf trusted execution environments. Supporting over one million events per second, we show that CUSTOS’ tamper-evident logging protocol is three orders of magnitude (1000×) faster than prior solutions and incurs only between 2% and 7% runtime overhead over insecure logging on intensive workloads. Further, we show that CUSTOS’ auditing protocol can detect violations in near realtime even in the presence of a powerful distributed adversary and with minimal (3%) network overhead. Our case study on a real-world APT attack scenario demonstrates that CUSTOS forces anti-forensic attackers into a “lose-lose” situation, where they can either be covert and not tamper with logs (which can be used for forensics), or erase logs but then be detected by CUSTOS.

Output:

> System auditing is a central concern when investigating and responding to security incidents. Unfortunately, attackers regularly engage in anti-forensic activities after a break-in, covering their tracks from the system logs in order to frustrate the efforts of investigators. While a variety of tamper-evident logging solutions have appeared throughout the industry and the literature, these techniques do not meet the operational and scalability requirements of system-layer audit frameworks. In this work, we introduce CUSTOS, a practical framework for the detection of tampering in system logs. CUSTOS consists of a tamper-evident logging layer and a decentralized auditing protocol. The former enables the verification of log integrity with minimal changes to the underlying logging framework, while the latter enables near real-time detection of log integrity violations within an enterprise-class network. CUSTOS is made practical by the observation that we can decouple the costs of cryptographic log commitments from the act of creating and storing log events, without trading off security, leveraging features of off-the-shelf trusted execution environments. Supporting over one million events per second, we show that CUSTOSâ tamper-evident logging protocol is three orders of magnitude (1000Ã) faster than prior solutions and incurs only between 2\% and 7\% runtime overhead over insecure logging on intensive workloads. Further, we show that CUSTOSâ auditing protocol can detect violations in near realtime even in the presence of a powerful distributed adversary and with minimal (3\%) network overhead. Our case study on a real-world APT attack scenario demonstrates that CUSTOS forces anti-forensic attackers into a âlose-loseâ

Notice:

- `(1000Ã)`
- `âlose-loseâ`

Also, not the full abstract is returned, as it seems.

**Comment by glad-dev** [comment]
Thank you for the bug report, the Unicode issue is resolved in version 0.3.

However, I was unable to reproduce the abstract getting cut off:
![cropped](https://user-images.githubusercontent.com/38458082/235365441-691c0cb0-e389-4f3b-aba7-98453d7814c6.png)

**Comment by vauhochzett** [comment]
True, for me neither, maybe that was a different issue.

And: Thanks! Godd fix. :+1:
